/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Controller;

/**
 *
 * @author Huyen
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnsach6 = new javax.swing.JPanel();
        jlbsach6 = new javax.swing.JLabel();
        jpnTheloai = new javax.swing.JPanel();
        jlbTheloai = new javax.swing.JLabel();
        jpnTacgia = new javax.swing.JPanel();
        jlbTacgia = new javax.swing.JLabel();
        jpnNxb = new javax.swing.JPanel();
        jlbNxb = new javax.swing.JLabel();
        jpnNhanvien = new javax.swing.JPanel();
        jlbNhanvien = new javax.swing.JLabel();
        jpnThongke = new javax.swing.JPanel();
        jlbThongke = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnsach6.setBackground(new java.awt.Color(255, 255, 255));

        jlbsach6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbsach6.setForeground(new java.awt.Color(0, 0, 0));
        jlbsach6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sach.png"))); // NOI18N
        jlbsach6.setText("  SÁCH");
        jlbsach6.setToolTipText("");

        javax.swing.GroupLayout jpnsach6Layout = new javax.swing.GroupLayout(jpnsach6);
        jpnsach6.setLayout(jpnsach6Layout);
        jpnsach6Layout.setHorizontalGroup(
            jpnsach6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnsach6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbsach6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnsach6Layout.setVerticalGroup(
            jpnsach6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnsach6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbsach6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnTheloai.setBackground(new java.awt.Color(255, 255, 255));

        jlbTheloai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbTheloai.setForeground(new java.awt.Color(0, 0, 0));
        jlbTheloai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/the_loai.png"))); // NOI18N
        jlbTheloai.setText("  THỂ LOẠI");

        javax.swing.GroupLayout jpnTheloaiLayout = new javax.swing.GroupLayout(jpnTheloai);
        jpnTheloai.setLayout(jpnTheloaiLayout);
        jpnTheloaiLayout.setHorizontalGroup(
            jpnTheloaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTheloaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTheloai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnTheloaiLayout.setVerticalGroup(
            jpnTheloaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTheloaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTheloai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnTacgia.setBackground(new java.awt.Color(255, 255, 255));

        jlbTacgia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbTacgia.setForeground(new java.awt.Color(0, 0, 0));
        jlbTacgia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tac_gia.png"))); // NOI18N
        jlbTacgia.setText("  TÁC GIẢ");

        javax.swing.GroupLayout jpnTacgiaLayout = new javax.swing.GroupLayout(jpnTacgia);
        jpnTacgia.setLayout(jpnTacgiaLayout);
        jpnTacgiaLayout.setHorizontalGroup(
            jpnTacgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTacgiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTacgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnTacgiaLayout.setVerticalGroup(
            jpnTacgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTacgiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTacgia, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnNxb.setBackground(new java.awt.Color(255, 255, 255));

        jlbNxb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbNxb.setForeground(new java.awt.Color(0, 0, 0));
        jlbNxb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/nxb.png"))); // NOI18N
        jlbNxb.setText("  NHÀ XUẤT BẢN");

        javax.swing.GroupLayout jpnNxbLayout = new javax.swing.GroupLayout(jpnNxb);
        jpnNxb.setLayout(jpnNxbLayout);
        jpnNxbLayout.setHorizontalGroup(
            jpnNxbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNxbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbNxb, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnNxbLayout.setVerticalGroup(
            jpnNxbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNxbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbNxb, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnNhanvien.setBackground(new java.awt.Color(255, 255, 255));

        jlbNhanvien.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbNhanvien.setForeground(new java.awt.Color(0, 0, 0));
        jlbNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/nhan_vien.png"))); // NOI18N
        jlbNhanvien.setText("  NHÂN VIÊN");

        javax.swing.GroupLayout jpnNhanvienLayout = new javax.swing.GroupLayout(jpnNhanvien);
        jpnNhanvien.setLayout(jpnNhanvienLayout);
        jpnNhanvienLayout.setHorizontalGroup(
            jpnNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnNhanvienLayout.setVerticalGroup(
            jpnNhanvienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNhanvienLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnThongke.setBackground(new java.awt.Color(255, 255, 255));
        jpnThongke.setPreferredSize(new java.awt.Dimension(216, 100));

        jlbThongke.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbThongke.setForeground(new java.awt.Color(0, 0, 0));
        jlbThongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/thong_ke.png"))); // NOI18N
        jlbThongke.setText("  THỐNG KÊ");

        javax.swing.GroupLayout jpnThongkeLayout = new javax.swing.GroupLayout(jpnThongke);
        jpnThongke.setLayout(jpnThongkeLayout);
        jpnThongkeLayout.setHorizontalGroup(
            jpnThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbThongke, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnThongkeLayout.setVerticalGroup(
            jpnThongkeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThongkeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbThongke)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 737, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(237, 237, 237)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jpnsach6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnTheloai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnTacgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnNxb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnNhanvien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jpnThongke, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                    .addGap(238, 238, 238)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 680, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jpnsach6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jpnTheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jpnTacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jpnNxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jpnNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jpnThongke, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbNhanvien;
    private javax.swing.JLabel jlbNxb;
    private javax.swing.JLabel jlbTacgia;
    private javax.swing.JLabel jlbTheloai;
    private javax.swing.JLabel jlbThongke;
    private javax.swing.JLabel jlbsach6;
    private javax.swing.JPanel jpnNhanvien;
    private javax.swing.JPanel jpnNxb;
    private javax.swing.JPanel jpnTacgia;
    private javax.swing.JPanel jpnTheloai;
    private javax.swing.JPanel jpnThongke;
    private javax.swing.JPanel jpnsach6;
    // End of variables declaration//GEN-END:variables
}
