/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bookshop;

import Bean.Danhmuc;
import Controller.Controller;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Huyen
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Trang chủ");
        this.setResizable(false);
        Controller controller = new Controller(jpnl_view);
//        controller.setView(jpnsach, jlbsach);
        
        List <Danhmuc> listItem = new ArrayList<>();
        listItem.add(new Danhmuc("Sách", jpnsach, jlbsach));
        listItem.add(new Danhmuc("Thể loại",jpnTheloai, jlbTheloai));
        listItem.add(new Danhmuc("Tác giả", jpnTacgia, jlbTacgia));
        listItem.add(new Danhmuc("Nhà xuất bản", jpnNxb, jlbNxb));
        
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jpnl_menu = new javax.swing.JPanel();
        jpnsach = new javax.swing.JPanel();
        jlbsach = new javax.swing.JLabel();
        jpnTheloai = new javax.swing.JPanel();
        jlbTheloai = new javax.swing.JLabel();
        jpnTacgia = new javax.swing.JPanel();
        jlbTacgia = new javax.swing.JLabel();
        jpnNxb = new javax.swing.JPanel();
        jlbNxb = new javax.swing.JLabel();
        btn_exit = new javax.swing.JButton();
        jpnl_view = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1091, 700));

        jpnl_menu.setBackground(new java.awt.Color(255, 255, 255));

        jpnsach.setBackground(new java.awt.Color(255, 255, 255));

        jlbsach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbsach.setForeground(new java.awt.Color(0, 0, 0));
        jlbsach.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/sach.png"))); // NOI18N
        jlbsach.setText("            SÁCH");
        jlbsach.setToolTipText("");

        javax.swing.GroupLayout jpnsachLayout = new javax.swing.GroupLayout(jpnsach);
        jpnsach.setLayout(jpnsachLayout);
        jpnsachLayout.setHorizontalGroup(
            jpnsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnsachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbsach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnsachLayout.setVerticalGroup(
            jpnsachLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnsachLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbsach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnTheloai.setBackground(new java.awt.Color(255, 255, 255));

        jlbTheloai.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbTheloai.setForeground(new java.awt.Color(0, 0, 0));
        jlbTheloai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/the_loai.png"))); // NOI18N
        jlbTheloai.setText("         THỂ LOẠI");

        javax.swing.GroupLayout jpnTheloaiLayout = new javax.swing.GroupLayout(jpnTheloai);
        jpnTheloai.setLayout(jpnTheloaiLayout);
        jpnTheloaiLayout.setHorizontalGroup(
            jpnTheloaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTheloaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTheloai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnTheloaiLayout.setVerticalGroup(
            jpnTheloaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTheloaiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTheloai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnTacgia.setBackground(new java.awt.Color(255, 255, 255));

        jlbTacgia.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbTacgia.setForeground(new java.awt.Color(0, 0, 0));
        jlbTacgia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tac_gia.png"))); // NOI18N
        jlbTacgia.setText("          TÁC GIẢ");

        javax.swing.GroupLayout jpnTacgiaLayout = new javax.swing.GroupLayout(jpnTacgia);
        jpnTacgia.setLayout(jpnTacgiaLayout);
        jpnTacgiaLayout.setHorizontalGroup(
            jpnTacgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTacgiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTacgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnTacgiaLayout.setVerticalGroup(
            jpnTacgiaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTacgiaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTacgia, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        jpnNxb.setBackground(new java.awt.Color(255, 255, 255));

        jlbNxb.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jlbNxb.setForeground(new java.awt.Color(0, 0, 0));
        jlbNxb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/nxb.png"))); // NOI18N
        jlbNxb.setText("     NHÀ XUẤT BẢN");

        javax.swing.GroupLayout jpnNxbLayout = new javax.swing.GroupLayout(jpnNxb);
        jpnNxb.setLayout(jpnNxbLayout);
        jpnNxbLayout.setHorizontalGroup(
            jpnNxbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNxbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbNxb, javax.swing.GroupLayout.DEFAULT_SIZE, 317, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnNxbLayout.setVerticalGroup(
            jpnNxbLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnNxbLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbNxb, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
                .addContainerGap())
        );

        btn_exit.setBackground(new java.awt.Color(255, 255, 255));
        btn_exit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        btn_exit.setForeground(new java.awt.Color(0, 0, 0));
        btn_exit.setText("Thoát");
        btn_exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_exitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpnl_menuLayout = new javax.swing.GroupLayout(jpnl_menu);
        jpnl_menu.setLayout(jpnl_menuLayout);
        jpnl_menuLayout.setHorizontalGroup(
            jpnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnsach, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnTheloai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnTacgia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnNxb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnl_menuLayout.createSequentialGroup()
                .addGap(57, 57, 57)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnl_menuLayout.setVerticalGroup(
            jpnl_menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_menuLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(jpnsach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnTheloai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnTacgia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnNxb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 125, Short.MAX_VALUE)
                .addComponent(btn_exit, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jpnl_view.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/nen.png"))); // NOI18N

        javax.swing.GroupLayout jpnl_viewLayout = new javax.swing.GroupLayout(jpnl_view);
        jpnl_view.setLayout(jpnl_viewLayout);
        jpnl_viewLayout.setHorizontalGroup(
            jpnl_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_viewLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 728, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jpnl_viewLayout.setVerticalGroup(
            jpnl_viewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnl_viewLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 672, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jpnl_menu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnl_view, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnl_view, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnl_menu, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_exitActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        LoginForm login =new LoginForm();
        login.setVisible(true);
    }//GEN-LAST:event_btn_exitActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new Home().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlbNxb;
    private javax.swing.JLabel jlbTacgia;
    private javax.swing.JLabel jlbTheloai;
    private javax.swing.JLabel jlbThongke;
    private javax.swing.JLabel jlbsach;
    private javax.swing.JPanel jpnNxb;
    private javax.swing.JPanel jpnTacgia;
    private javax.swing.JPanel jpnTheloai;
    private javax.swing.JPanel jpnThongke;
    private javax.swing.JPanel jpnl_menu;
    private javax.swing.JPanel jpnl_view;
    private javax.swing.JPanel jpnsach;
    // End of variables declaration//GEN-END:variables
}
