/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bookshop;
import java.awt.Graphics;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.IOException;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Huyen
 */
public class Nhanvien extends javax.swing.JPanel {

    ConnectDataBase db = new ConnectDataBase();
    Connection conn;
    
    public Nhanvien() {
        initComponents();
        HienThi();
        HienThitb2();
        txt_TongLuong.setEnabled(false);
        LoadDataCmb();
    }

    public void LoadDataCmb(){
        conn =  db.getConnection();
        String query1 = "Select * from NhanVien";
        try{
            PreparedStatement ps = conn.prepareStatement(query1);
            ResultSet rs = ps.executeQuery();
            while(rs.next())
            {
                this.cmb_manv.addItem(rs.getString("HoTen"));
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e, "Lỗi",1);
        }
    }
    
    private  void loadLai(){
        txt_MaNV.setText("");
        txt_HoTen.setText("");
        txt_SoDienThoai.setText("");
        cbb_Ngay.setSelectedIndex(1);
        cbb_Thang.setSelectedIndex(1);
        cbb_Nam.setSelectedIndex(20);
        txt_QueQuan.setText("");
        txt_DiaChiHienTai.setText("");
        txt_HeSoLuong.setText("");
        txt_TimKiem.setText("");
    }
    
    private  void loadLaitb2(){
        cmb_manv.setSelectedIndex(0);
        txt_Thang.setText("");
        txt_SoCong.setText("");
        txt_Thuong.setText("");
        txt_Phat.setText("");
        txt_TongLuong.setText("");
    }
    
    
    public void HienThi(){
        conn =  db.getConnection();

        try {
            Statement st =  conn.createStatement();
            String query = "Select * from NhanVien";
            ResultSet rs =  st.executeQuery(query);
            DefaultTableModel model  = new DefaultTableModel();
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            for(int columnIndex = 1; columnIndex <= columnCount; columnIndex++) 
            {
                model.addColumn(metaData.getColumnLabel(columnIndex));
            }
            while(rs.next()) 
            {
                Object[] rowData = new Object[columnCount];
                for(int i=0; i<columnCount; i++) 
                {
                    rowData[i] = rs.getObject(i + 1); 
                }
                model.addRow(rowData);
            }
            table_NhanVien.setModel(model);
            st.close();
            rs.close();
            conn.close();
	} catch (SQLException e1) {
            e1.toString();
	}
    }
    
    public void HienThitb2(){
        conn =  db.getConnection();

        try {
            Statement st =  conn.createStatement();
            String query = "Select * from Luong";
            ResultSet rs =  st.executeQuery(query);
            DefaultTableModel model  = new DefaultTableModel();
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            for(int columnIndex = 1; columnIndex <= columnCount; columnIndex++) 
            {
                model.addColumn(metaData.getColumnLabel(columnIndex));
            }
            while(rs.next()) 
            {
                Object[] rowData = new Object[columnCount];
                for(int i=0; i<columnCount; i++) 
                {
                    rowData[i] = rs.getObject(i + 1); 
                }
                model.addRow(rowData);
            }
            table_Luong.setModel(model);
            st.close();
            rs.close();
            conn.close();
	} catch (SQLException e1) {
            e1.toString();
	}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupGT = new javax.swing.ButtonGroup();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        rbtn_Nam = new javax.swing.JRadioButton();
        rbtn_Nu = new javax.swing.JRadioButton();
        jLabel33 = new javax.swing.JLabel();
        txt_MaNV = new javax.swing.JTextField();
        jLabel34 = new javax.swing.JLabel();
        txt_HoTen = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        txt_SoDienThoai = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        cbb_Ngay = new javax.swing.JComboBox<>();
        cbb_Thang = new javax.swing.JComboBox<>();
        cbb_Nam = new javax.swing.JComboBox<>();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        btn_Xoa = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        txt_TimKiem = new javax.swing.JTextField();
        btn_TimKiem = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        txt_QueQuan = new javax.swing.JTextField();
        txt_DiaChiHienTai = new javax.swing.JTextField();
        txt_HeSoLuong = new javax.swing.JTextField();
        label_AnhNV = new javax.swing.JLabel();
        btn_ChonAnh = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table_NhanVien = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_Luong = new javax.swing.JTable();
        jLabel17 = new javax.swing.JLabel();
        txt_Thang = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txt_SoCong = new javax.swing.JTextField();
        txt_Thuong = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        txt_TongLuong = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        txt_Phat = new javax.swing.JTextField();
        btn_ThemLuong = new javax.swing.JButton();
        btn_SuaLuong = new javax.swing.JButton();
        btn_XoaLuong = new javax.swing.JButton();
        btn_LamMoiLuong = new javax.swing.JButton();
        btn_TimKiemLuong = new javax.swing.JButton();
        txt_timkiemluong = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        cmb_manv = new javax.swing.JComboBox<>();
        jLabel22 = new javax.swing.JLabel();
        txt_Nam = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentShown(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        rbtn_Nam.setBackground(new java.awt.Color(255, 255, 255));
        btngroupGT.add(rbtn_Nam);
        rbtn_Nam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtn_Nam.setText("Nam");

        rbtn_Nu.setBackground(new java.awt.Color(255, 255, 255));
        btngroupGT.add(rbtn_Nu);
        rbtn_Nu.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        rbtn_Nu.setText("Nữ");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbtn_Nam)
                .addGap(18, 18, 18)
                .addComponent(rbtn_Nu)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 8, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbtn_Nam)
                    .addComponent(rbtn_Nu)))
        );

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 0, 0));
        jLabel33.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel33.setText("Mã nhân viên:");

        txt_MaNV.setBackground(new java.awt.Color(255, 255, 255));
        txt_MaNV.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_MaNV.setForeground(new java.awt.Color(0, 0, 0));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 0, 0));
        jLabel34.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel34.setText("Họ tên:");

        txt_HoTen.setBackground(new java.awt.Color(255, 255, 255));
        txt_HoTen.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_HoTen.setForeground(new java.awt.Color(0, 0, 0));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 0, 0));
        jLabel35.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel35.setText("Số điện thoại:");

        txt_SoDienThoai.setBackground(new java.awt.Color(255, 255, 255));
        txt_SoDienThoai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_SoDienThoai.setForeground(new java.awt.Color(0, 0, 0));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 0, 0));
        jLabel36.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel36.setText("Giới tính:");

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel12.setText("Ngày Sinh:");

        cbb_Ngay.setBackground(new java.awt.Color(255, 255, 255));
        cbb_Ngay.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbb_Ngay.setForeground(new java.awt.Color(0, 0, 0));
        cbb_Ngay.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        cbb_Thang.setBackground(new java.awt.Color(255, 255, 255));
        cbb_Thang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbb_Thang.setForeground(new java.awt.Color(0, 0, 0));
        cbb_Thang.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cbb_Thang.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbb_ThangItemStateChanged(evt);
            }
        });
        cbb_Thang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbb_ThangActionPerformed(evt);
            }
        });

        cbb_Nam.setBackground(new java.awt.Color(255, 255, 255));
        cbb_Nam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbb_Nam.setForeground(new java.awt.Color(0, 0, 0));
        cbb_Nam.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        btn_Them.setBackground(new java.awt.Color(255, 255, 255));
        btn_Them.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Them.setForeground(new java.awt.Color(0, 0, 0));
        btn_Them.setText("Thêm");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(255, 255, 255));
        btn_Sua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(0, 0, 0));
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        btn_Xoa.setBackground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(0, 0, 0));
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_LamMoi.setBackground(new java.awt.Color(255, 255, 255));
        btn_LamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_LamMoi.setForeground(new java.awt.Color(0, 0, 0));
        btn_LamMoi.setText("Reset");
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(0, 0, 0));
        jLabel37.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel37.setText("Tìm kiếm:");

        txt_TimKiem.setBackground(new java.awt.Color(255, 255, 255));
        txt_TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_TimKiem.setForeground(new java.awt.Color(0, 0, 0));

        btn_TimKiem.setBackground(new java.awt.Color(255, 255, 255));
        btn_TimKiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_TimKiem.setForeground(new java.awt.Color(0, 0, 0));
        btn_TimKiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        btn_TimKiem.setText("Tìm kiếm");
        btn_TimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(0, 0, 0));
        jLabel38.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel38.setText("Hệ số lương:");

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 0, 0));
        jLabel39.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel39.setText("Địa chỉ:");

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(0, 0, 0));
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel40.setText("Quê quán:");

        txt_QueQuan.setBackground(new java.awt.Color(255, 255, 255));
        txt_QueQuan.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_QueQuan.setForeground(new java.awt.Color(0, 0, 0));

        txt_DiaChiHienTai.setBackground(new java.awt.Color(255, 255, 255));
        txt_DiaChiHienTai.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_DiaChiHienTai.setForeground(new java.awt.Color(0, 0, 0));

        txt_HeSoLuong.setBackground(new java.awt.Color(255, 255, 255));
        txt_HeSoLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_HeSoLuong.setForeground(new java.awt.Color(0, 0, 0));

        label_AnhNV.setBackground(new java.awt.Color(255, 255, 255));

        btn_ChonAnh.setBackground(new java.awt.Color(255, 255, 255));
        btn_ChonAnh.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_ChonAnh.setForeground(new java.awt.Color(0, 0, 0));
        btn_ChonAnh.setText("Chọn ảnh");
        btn_ChonAnh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ChonAnhActionPerformed(evt);
            }
        });

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        table_NhanVien.setBackground(new java.awt.Color(255, 255, 255));
        table_NhanVien.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_NhanVien.setForeground(new java.awt.Color(0, 0, 0));
        table_NhanVien.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_NhanVien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_NhanVienMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(table_NhanVien);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel36)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbb_Ngay, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbb_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbb_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 503, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel35)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_SoDienThoai)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel38)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txt_HeSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btn_TimKiem)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_DiaChiHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(274, 274, 274))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel40)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(btn_ChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(93, 93, 93))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(txt_QueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(label_AnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(37, 37, 37))))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(txt_HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39)
                    .addComponent(txt_DiaChiHienTai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(txt_SoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel38)
                    .addComponent(txt_HeSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel36)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbb_Ngay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbb_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbb_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel12))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel37)
                    .addComponent(btn_TimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(357, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel33)
                            .addComponent(txt_MaNV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_QueQuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel40))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(label_AnhNV, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(btn_ChonAnh, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(46, 46, 46)))
        );

        jTabbedPane2.addTab("Quản lý nhân viên", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        table_Luong.setBackground(new java.awt.Color(255, 255, 255));
        table_Luong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_Luong.setForeground(new java.awt.Color(0, 0, 0));
        table_Luong.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_Luong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_LuongMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_Luong);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(0, 0, 0));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel17.setText("Mã Nhân viên:");

        txt_Thang.setBackground(new java.awt.Color(255, 255, 255));
        txt_Thang.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Thang.setForeground(new java.awt.Color(0, 0, 0));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 0, 0));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel18.setText("Tháng:");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(0, 0, 0));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel19.setText("Số Công:");

        txt_SoCong.setBackground(new java.awt.Color(255, 255, 255));
        txt_SoCong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_SoCong.setForeground(new java.awt.Color(0, 0, 0));

        txt_Thuong.setBackground(new java.awt.Color(255, 255, 255));
        txt_Thuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Thuong.setForeground(new java.awt.Color(0, 0, 0));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(0, 0, 0));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel20.setText("Thưởng:");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/nhan_vien.png"))); // NOI18N

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(0, 0, 0));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel23.setText("TỔNG LƯƠNG:");

        txt_TongLuong.setBackground(new java.awt.Color(255, 255, 255));
        txt_TongLuong.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        txt_TongLuong.setForeground(new java.awt.Color(0, 0, 0));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(0, 0, 0));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel24.setText("Phạt:");

        txt_Phat.setBackground(new java.awt.Color(255, 255, 255));
        txt_Phat.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Phat.setForeground(new java.awt.Color(0, 0, 0));

        btn_ThemLuong.setBackground(new java.awt.Color(255, 255, 255));
        btn_ThemLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_ThemLuong.setForeground(new java.awt.Color(0, 0, 0));
        btn_ThemLuong.setText("Tính lương");
        btn_ThemLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemLuongActionPerformed(evt);
            }
        });

        btn_SuaLuong.setBackground(new java.awt.Color(255, 255, 255));
        btn_SuaLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_SuaLuong.setForeground(new java.awt.Color(0, 0, 0));
        btn_SuaLuong.setText("Sửa");
        btn_SuaLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaLuongActionPerformed(evt);
            }
        });

        btn_XoaLuong.setBackground(new java.awt.Color(255, 255, 255));
        btn_XoaLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_XoaLuong.setForeground(new java.awt.Color(0, 0, 0));
        btn_XoaLuong.setText("Xóa");
        btn_XoaLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaLuongActionPerformed(evt);
            }
        });

        btn_LamMoiLuong.setBackground(new java.awt.Color(255, 255, 255));
        btn_LamMoiLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_LamMoiLuong.setForeground(new java.awt.Color(0, 0, 0));
        btn_LamMoiLuong.setText("Reset");
        btn_LamMoiLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiLuongActionPerformed(evt);
            }
        });

        btn_TimKiemLuong.setBackground(new java.awt.Color(255, 255, 255));
        btn_TimKiemLuong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_TimKiemLuong.setForeground(new java.awt.Color(0, 0, 0));
        btn_TimKiemLuong.setText("Tìm kiếm");
        btn_TimKiemLuong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_TimKiemLuongActionPerformed(evt);
            }
        });

        txt_timkiemluong.setBackground(new java.awt.Color(255, 255, 255));
        txt_timkiemluong.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_timkiemluong.setForeground(new java.awt.Color(0, 0, 0));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(0, 0, 0));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel21.setText("Tìm kiếm:");

        cmb_manv.setBackground(new java.awt.Color(255, 255, 255));
        cmb_manv.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cmb_manv.setForeground(new java.awt.Color(0, 0, 0));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(0, 0, 0));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel22.setText("Năm:");

        txt_Nam.setBackground(new java.awt.Color(255, 255, 255));
        txt_Nam.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_Nam.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt_timkiemluong, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_TimKiemLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_manv, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                        .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txt_Phat, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 1, Short.MAX_VALUE))
                                    .addComponent(txt_Thuong)
                                    .addComponent(txt_SoCong)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_Nam)
                                    .addComponent(txt_Thang))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btn_ThemLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_LamMoiLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btn_SuaLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btn_XoaLuong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(txt_TongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel23)
                                .addGap(24, 24, 24)))
                        .addGap(32, 32, 32)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cmb_manv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Thang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel22))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_SoCong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(txt_Thuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel24)
                            .addComponent(txt_Phat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(txt_TongLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btn_ThemLuong)
                                    .addComponent(btn_SuaLuong)))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_LamMoiLuong)
                            .addComponent(btn_XoaLuong))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(txt_timkiemluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_TimKiemLuong))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 364, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jTabbedPane2.addTab("Quản lý lương nhân viên", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    boolean getGT(String GT){
        return "Nam".equals(GT);
    }
        
    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        rbtn_Nam.setSelected(true);
        HienThi();
        for (int i = 1; i < 32; i++) {
            cbb_Ngay.addItem(String.valueOf(i));
        }
        for (int i = 1; i < 13; i++) {
            cbb_Thang.addItem(String.valueOf(i));
        }
        for (int i = 2010; i > 1950; i--) {
            cbb_Nam.addItem(String.valueOf(i));
        }
    }//GEN-LAST:event_formComponentShown

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_jTabbedPane2StateChanged

    private void jPanel1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentShown
        rbtn_Nam.setSelected(true);
        HienThi();
        for (int i = 1; i < 32; i++) {
            cbb_Ngay.addItem(String.valueOf(i));
        }
        for (int i = 1; i < 13; i++) {
            cbb_Thang.addItem(String.valueOf(i));
        }
        for (int i = 2010; i > 1950; i--) {
            cbb_Nam.addItem(String.valueOf(i));
        }
    }//GEN-LAST:event_jPanel1ComponentShown

    private void cbb_ThangItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbb_ThangItemStateChanged
        int tam=0;
        String thang = cbb_Thang.getSelectedItem().toString();
        DefaultComboBoxModel cbbmodel = new DefaultComboBoxModel();
        String thanght;
        if (tam == 0) {
            thanght = "0";
        } else {
            thanght = cbb_Ngay.getSelectedItem().toString();
        }
        tam = 1;

        switch (thang) {
            case "4", "6", "9", "11" -> {
                cbb_Ngay.setModel(cbbmodel);
                for (int i = 1; i < 31; i++) {
                    cbb_Ngay.addItem(String.valueOf(i));
                }   if (Integer.parseInt(thanght) < 31) {
                    cbb_Ngay.setSelectedItem(thanght);
                }
            }
            case "1", "3", "5", "7", "8", "12", "10" -> {
                cbb_Ngay.setModel(cbbmodel);
                for (int i = 1; i < 32; i++) {
                    cbb_Ngay.addItem(String.valueOf(i));
                }   if (Integer.parseInt(thanght) < 32) {
                    cbb_Ngay.setSelectedItem(thanght);
                }
            }
            default -> {
                cbb_Ngay.setModel(cbbmodel);
                for (int i = 1; i < 29; i++) {
                    cbb_Ngay.addItem(String.valueOf(i));
                }   if (Integer.parseInt(thanght) < 29) {
                    cbb_Ngay.setSelectedItem(thanght);
                }
            }
        }
    }//GEN-LAST:event_cbb_ThangItemStateChanged

    private void cbb_ThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbb_ThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbb_ThangActionPerformed

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        conn = db.getConnection();
        try{
            String MaNV, HoTen, SDT, GioiTinh, NgaySinh, QueQuan, DiaChiHienTai, HeSoLuong;
            MaNV = txt_MaNV.getText();
            HoTen = txt_HoTen.getText();
            SDT = txt_SoDienThoai.getText();
            QueQuan = txt_QueQuan.getText();
            DiaChiHienTai = txt_DiaChiHienTai.getText();
            HeSoLuong = txt_HeSoLuong.getText();
            String ngay, thang, nam;
            ngay = cbb_Ngay.getSelectedItem().toString();
            thang = cbb_Thang.getSelectedItem().toString();
            nam = cbb_Nam.getSelectedItem().toString();
            NgaySinh = nam + "-" + thang + "-" + ngay;
            if (rbtn_Nam.isSelected()) {
                GioiTinh = "Nam";
            } else {
                GioiTinh = "Nu";
            }
            byte[] anhcanhan = null;
            if (label_AnhNV.getIcon() != null) {
                ImageIcon imageIcon = (ImageIcon) label_AnhNV.getIcon();
                BufferedImage bufferedImage = new BufferedImage(imageIcon.getIconWidth(), imageIcon.getIconHeight(), BufferedImage.TYPE_INT_RGB);
                Graphics graphics = bufferedImage.createGraphics();
                imageIcon.paintIcon(null, graphics, 0, 0);
                graphics.dispose();
                ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
                try {
                    ImageIO.write(bufferedImage, "jpg", byteArrayOutputStream);
                } catch (IOException e) {
                }
                anhcanhan = byteArrayOutputStream.toByteArray();
            }
            if(MaNV.equals("")||HoTen.equals("")||SDT.equals("")||QueQuan.equals("")||DiaChiHienTai.equals("")||HeSoLuong.equals("")){
                JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ dữ liệu");
            }else{
                float hsl=0;
                if(!HeSoLuong.isEmpty()){
                    hsl = Float.parseFloat(HeSoLuong);
                }
                if(hsl<=0){
                    JOptionPane.showMessageDialog(this, "Hệ số lương phải lớn hơn 0", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if(MaNV.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Thêm Thất Bại!");
                }

                try {
                    if(MaNV.equals("")||HoTen.equals("")||
                        SDT.equals("")||QueQuan.equals("")||DiaChiHienTai.equals("")||HeSoLuong.equals("")){
                        JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ dữ liệu");
                    }else{
                        StringBuffer sb = new StringBuffer();
                        String querry = "select MaNV from NhanVien where MaNV = '"+MaNV+"'";
                        Statement st = conn.createStatement();
                        ResultSet rs = st.executeQuery(querry);
                        if(rs.next()){
                            sb.append("Mã nhân viên này đã tồn tại");
                        }
                        if(sb.length() > 0){//nếu if kia đúng thig nó sẽ thêm vào sb 1 đoạn string,ktra độ dài chuỗi này nếu lớn hơn 0 tức là có thông báo
                            JOptionPane.showMessageDialog(this, sb.toString());
                        }else{
                            PreparedStatement ps = conn.prepareStatement("insert into NhanVien values (?, ?, ?, ?, ?, ?, ?, ?, ?)");
                            ps.setNString(1, MaNV);
                            ps.setNString(2, HoTen);
                            ps.setNString(3, SDT);
                            ps.setNString(4, GioiTinh);
                            ps.setNString(5, NgaySinh);
                            ps.setNString(6, QueQuan);
                            ps.setNString(7, DiaChiHienTai);
                            ps.setFloat(8, hsl);
                            ps.setBytes(9, anhcanhan);
                            int kq = ps.executeUpdate();
                            if(kq>0){
                                JOptionPane.showMessageDialog(this, "Thêm thành công");
                                loadLai();
                                HienThi();
                            }else{
                                JOptionPane.showMessageDialog(this, "Thêm thất bại");
                            }
                            st.close();
                            ps.close();
                        }
                        conn.close();
                    }
                } catch (HeadlessException | SQLException e) {
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số, không nhập chữ vào ô Hệ số lương");
            System.out.println("Lỗi: " + ex.getMessage());
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        try{
            String MaNV, HoTen, SDT, GioiTinh, NgaySinh, QueQuan, DiaChiHienTai, HeSoLuong;
            MaNV = txt_MaNV.getText();
            HoTen = txt_HoTen.getText();
            SDT = txt_SoDienThoai.getText();
            QueQuan = txt_QueQuan.getText();
            DiaChiHienTai = txt_DiaChiHienTai.getText();
            HeSoLuong = txt_HeSoLuong.getText();
            String ngay, thang, nam;
            thang = cbb_Thang.getSelectedItem().toString();
            ngay = cbb_Ngay.getSelectedItem().toString();
            nam = cbb_Nam.getSelectedItem().toString();
            NgaySinh = nam + "-" + thang + "-" + ngay;
            if (rbtn_Nam.isSelected()) {
                GioiTinh = "Nam";
            } else {
                GioiTinh = "Nu";
            }
            byte[] anhcanhan = null;
            if (label_AnhNV.getIcon() != null) {
                ImageIcon imageIcon = (ImageIcon) label_AnhNV.getIcon();
                BufferedImage bufferedImage = new BufferedImage(imageIcon.getIconWidth(), imageIcon.getIconHeight(), BufferedImage.TYPE_INT_RGB);
                Graphics graphics = bufferedImage.createGraphics();
                imageIcon.paintIcon(null, graphics, 0, 0);
                graphics.dispose();
                ByteArrayOutputStream byteArrayOutputStream = new ByteArrayOutputStream();
                try {
                    ImageIO.write(bufferedImage, "jpg", byteArrayOutputStream);
                } catch (IOException e) {
                }
                anhcanhan = byteArrayOutputStream.toByteArray();
            }
            float hsl=0;
            if(MaNV.equals("")||HoTen.equals("")||SDT.equals("")||
                QueQuan.equals("")||DiaChiHienTai.equals("")||HeSoLuong.equals("")){
                JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ dữ liệu");
            }else{
                if(!HeSoLuong.isEmpty()){
                    hsl = Float.parseFloat(HeSoLuong);
                }
                if(hsl<=0){
                    JOptionPane.showMessageDialog(this, "Hệ số lương phải lớn hơn 0", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if(MaNV.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Sửa Thất Bại!");
                }

                conn = db.getConnection();
                try {
                    if(MaNV.equals("")||HoTen.equals("")||SDT.equals("")||
                        QueQuan.equals("")||DiaChiHienTai.equals("")||HeSoLuong.equals("")){
                        JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ dữ liệu");
                    }else{
                        PreparedStatement ps = conn.prepareStatement("Update NhanVien set HoTen = ?, SoDienThoai = ?, GioiTinh = ?, NgaySinh = ?, "
                            + "QueQuan = ?, DiaChiHienTai = ?, HeSoLuong = ?, AnhCaNhan = ? where MaNV = ?");
                        ps.setNString(1, HoTen);
                        ps.setNString(2, SDT);
                        ps.setNString(3, GioiTinh);
                        ps.setNString(4, NgaySinh);
                        ps.setNString(5, QueQuan);
                        ps.setNString(6, DiaChiHienTai);
                        ps.setFloat(7, hsl);
                        ps.setBytes(8, anhcanhan);
                        ps.setNString(9, MaNV);
                        int kq = ps.executeUpdate();
                        if(kq>0){
                            JOptionPane.showMessageDialog(this, "Sửa thành công");
                            loadLai();
                            HienThi();
                        }else{
                            JOptionPane.showMessageDialog(this, "Sửa thất bại");
                        }
                        ps.close();
                    }
                    conn.close();
                } catch (HeadlessException | SQLException e) {
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số không nhập chữ vào ô Hệ số lương");
            System.out.println("Lỗi: " + ex.getMessage());
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        conn =  db.getConnection();
        String manv = txt_MaNV.getText();
        try {
            if(txt_MaNV.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Bạn cần nhập dữ liệu mã nhân viên để xóa thông tin");
            }else{
                PreparedStatement ps = conn.prepareStatement("Delete from NhanVien where MaNV = ? ");
                ps.setNString(1, manv);
                int rowDelete = ps.executeUpdate();
                if(rowDelete > 0)
                {
                    int t = JOptionPane.showConfirmDialog(this,"Ban co muon xoa?","Thong bao!", JOptionPane.YES_NO_OPTION);
                    if(t == JOptionPane.YES_OPTION){
                        JOptionPane.showMessageDialog(this, "Xóa thành công");
                        loadLai();HienThi();
                    }else{
                        JOptionPane.showMessageDialog(this, "Xóa thất bại");
                    }
                }else {
                    JOptionPane.showMessageDialog(this, "Xóa Thất Bại!\nBạn cần xóa dữ liệu của nhân có mã nhân viên tương ứng trên bảng tính lương trước để thực hiện yêu cầu xóa");
                }
                ps.close();
                conn.close();
            }
        }catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Xóa Thất Bại!\nBạn cần xóa dữ liệu của nhân viên có mã nhân viên tương ứng trên bảng tính lương trước để thực hiện yêu cầu xóa", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        // TODO add your handling code here:
        txt_MaNV.setText("");
        txt_HoTen.setText("");
        txt_SoDienThoai.setText("");
        rbtn_Nam.setSelected(true);
        cbb_Ngay.setSelectedIndex(WIDTH);
        cbb_Thang.setSelectedIndex(WIDTH);
        cbb_Nam.setSelectedIndex(WIDTH);
        txt_QueQuan.setText("");
        txt_DiaChiHienTai.setText("");
        txt_HeSoLuong.setText("");
        label_AnhNV.setIcon(null);
        HienThi();

        txt_MaNV.setEnabled(true);
        btn_Them.setEnabled(true);
        btn_Sua.setEnabled(false);
        btn_Xoa.setEnabled(false);
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void btn_TimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemActionPerformed
        // TODO add your handling code here:
        conn = db.getConnection();
        try {
            if(txt_TimKiem.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Bạn cần nhập tên nhân viên vào ô 'Nhập thông tin tìm kiếm'");
            }else{
                PreparedStatement ps = conn.prepareStatement("SELECT * FROM NhanVien WHERE HoTen LIKE ?");
                ps.setNString(1, "%" + txt_TimKiem.getText() + "%");
                ResultSet rs = ps.executeQuery();
                DefaultTableModel model = (DefaultTableModel) table_NhanVien.getModel();
                model.setRowCount(0);
                while (rs.next()) {
                    Object[] rowData = {rs.getString("MaNV"), rs.getString("HoTen"), rs.getString("SoDienThoai"),
                        rs.getString("GioiTinh"), rs.getString("NgaySinh"), rs.getString("QueQuan"),
                        rs.getString("DiaChiHienTai"),rs.getFloat("HeSoLuong"), null};

                    Blob b = rs.getBlob("AnhCaNhan");
                    if (b != null) {
                        byte[] imageBytes = b.getBytes(1, (int) b.length());
                        ImageIcon anhcanhan = new ImageIcon(imageBytes);
                        rowData[8] = anhcanhan;
                    } else {
                        rowData[8] = null;
                    }

                    model.addRow(rowData);
                }

                if (model.getRowCount() > 0) {
                    JOptionPane.showMessageDialog(this, "Có " + model.getRowCount() + " nhân viên mà bạn muốn tìm!");
                } else {
                    JOptionPane.showMessageDialog(this, "Không có nhân viên nào!");
                }

                conn.close();
            }
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu: " + e.getMessage(), "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_TimKiemActionPerformed

    private void btn_ChonAnhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ChonAnhActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        if (file != null) {
            ImageIcon imageIcon = new ImageIcon(file.getAbsolutePath());
            Image image = imageIcon.getImage().getScaledInstance(label_AnhNV.getWidth(), label_AnhNV.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(image);
            label_AnhNV.setIcon(scaledIcon);
        }
    }//GEN-LAST:event_btn_ChonAnhActionPerformed

    private void table_NhanVienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_NhanVienMouseClicked
        // TODO add your handling code here:
        table_NhanVien.setDefaultEditor(Object.class, null);
        int i = table_NhanVien.getSelectedRow();
        table_NhanVien.setDefaultEditor(Object.class, null);
        if(i>=0){
            txt_MaNV.setText(table_NhanVien.getValueAt(i, 0) + "");
            txt_HoTen.setText(table_NhanVien.getValueAt(i, 1) + "");
            txt_SoDienThoai.setText(table_NhanVien.getValueAt(i, 2) + "");
            String GioiTinh = table_NhanVien.getValueAt(i, 3).toString();
            if(true==getGT(GioiTinh)){
                rbtn_Nam.setSelected(true);
            }else{
                rbtn_Nu.setSelected(true);
            }
            String date = table_NhanVien.getModel().getValueAt(i, 4).toString();
            String[] parts;
            parts = date.split("-");
            String year = parts[0];
            cbb_Nam.setSelectedItem(year);

            String month = parts[1]; 
            if(month.indexOf("0") == 0){
                month = month.replace("0", "");
                cbb_Thang.setSelectedItem(month);
            }else{
                cbb_Thang.setSelectedItem(month);
            }
            
            String day = parts[2];
            if(day.indexOf("0")== 0){
                day = day.replace("0", "");
                cbb_Ngay.setSelectedItem(day);
            }else{
                cbb_Ngay.setSelectedItem(day);
            }
            
            txt_QueQuan.setText(table_NhanVien.getValueAt(i, 5) + "");
            txt_DiaChiHienTai.setText(table_NhanVien.getValueAt(i, 6) + "");
            txt_HeSoLuong.setText(table_NhanVien.getValueAt(i, 7) + "");
            byte[] imageData = (byte[]) table_NhanVien.getValueAt(i, 8);
            if (imageData != null) {
                ImageIcon imageIcon = new ImageIcon(imageData);
                Image image = imageIcon.getImage().getScaledInstance(label_AnhNV.getWidth(), label_AnhNV.getHeight(), Image.SCALE_SMOOTH);
                label_AnhNV.setIcon(new ImageIcon(image));
            } else {
                label_AnhNV.setIcon(null);
            }
        }
        txt_MaNV.setEnabled(false);
        btn_Them.setEnabled(false);
        btn_Sua.setEnabled(true);
        btn_Xoa.setEnabled(true);
    }//GEN-LAST:event_table_NhanVienMouseClicked

    private void table_LuongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_LuongMouseClicked
        // TODO add your handling code here:
        conn =  db.getConnection();

        table_Luong.setDefaultEditor(Object.class, null);
        
        try{
            int row = table_Luong.getSelectedRow();
            if (row >= 0) {
                String maNv = (String) table_Luong.getValueAt(row, 0);
                String thang = table_Luong.getValueAt(row, 1).toString();
                txt_Nam.setText(table_Luong.getValueAt(row, 2) + "");
                String socong = table_Luong.getValueAt(row, 3).toString();
                String thuong = table_Luong.getValueAt(row, 4).toString();
                String phat = table_Luong.getValueAt(row, 5).toString();
                String tongluong = table_Luong.getValueAt(row, 6).toString();

                String tennhanvien = null;
                PreparedStatement ps1 = conn.prepareStatement("SELECT HoTen FROM NhanVien WHERE MaNV = ?");
                ps1.setString(1, maNv);
                ResultSet rs1 = ps1.executeQuery();
                if (rs1.next()) {
                    tennhanvien = rs1.getNString("HoTen");
                }

                if (tennhanvien != null)
                {
                    for (int i = 0; i < cmb_manv.getItemCount(); i++) {
                        String theLoaiValue = cmb_manv.getItemAt(i).toString();
                        if (theLoaiValue.equals(tennhanvien))
                        {
                            cmb_manv.setSelectedIndex(i);
                            break;
                        }
                    }
                }

                txt_Thang.setText(thang);
                txt_SoCong.setText(socong);
                txt_Thuong.setText(thuong);
                txt_Phat.setText(phat);
                txt_TongLuong.setText(tongluong);

                cmb_manv.setEnabled(false);
                txt_Thang.setEnabled(false);
                txt_Nam.setEnabled(false);
                btn_ThemLuong.setEnabled(false);
                btn_SuaLuong.setEnabled(true);
                btn_XoaLuong.setEnabled(true);

            }
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu: " + e.getMessage(), "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_table_LuongMouseClicked

    private void btn_ThemLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemLuongActionPerformed
        // TODO add your handling code here:
        try{
            String MaNV, Thang, Nam, SoCong, Thuong, Phat;
            MaNV = (String) cmb_manv.getSelectedItem();
            Thang = txt_Thang.getText() ;
            Nam = txt_Nam.getText();
            SoCong = txt_SoCong.getText();
            Thuong = txt_Thuong.getText();
            Phat = txt_Phat.getText();

            int thang=0, nam=0;
            float socong=0, thuong=0, phat=0;
            if(!Thang.isEmpty() && !Nam.isEmpty() && !SoCong.isEmpty() && !Thuong.isEmpty() && !Phat.isEmpty()){
                thang = Integer.parseInt(Thang);
                nam = Integer.parseInt(Nam);
                socong = Float.parseFloat(SoCong);
                thuong = Float.parseFloat(Thuong);
                phat = Float.parseFloat(Phat);

            }
            if(MaNV.equals("") || Thang.equals("") || Nam.equals("") ||
                        SoCong.equals("") || Thuong.equals("") || Phat.equals("")){
                    JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ dữ liệu");
            }else{
                if(thang<=0 || thang >12 || nam<=0 || nam>2023 || socong < 0 || thuong < 0 || phat < 0){
                    JOptionPane.showMessageDialog(this, "Có giá trị nhập không hợp lệ", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if(MaNV.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Thêm Thất Bại!");
                }

                conn = db.getConnection();
                try {
                    StringBuffer sb = new StringBuffer();
                    String querry = "select * from Luong where Thang = '" +Thang+ "' and Nam = '" +Nam+ "'";
                    Statement st = conn.createStatement();
                    ResultSet rs = st.executeQuery(querry);
                    if(rs.next()){
                        sb.append("Tháng lương của nhân viên này đã tồn tại trong bảng lương!");
                    }
                    if(sb.length() > 0){
                        JOptionPane.showMessageDialog(this, sb.toString());
                    }else{
                        PreparedStatement ps = conn.prepareStatement("insert into Luong values ((SELECT MaNV FROM NhanVien WHERE HoTen = ?),?, ?, ?, ?, ?, ?)");
                        ps.setNString(1, MaNV);
                        ps.setInt(2, thang);
                        ps.setInt(3, nam);
                        ps.setFloat(4, socong);
                        ps.setFloat(5, thuong);
                        ps.setFloat(6, phat);
                        ps.setString(7, null);
                        int kq = ps.executeUpdate();
                        if(kq>0){
                            JOptionPane.showMessageDialog(this, "Tính lương thành công");
                            loadLaitb2();
                            HienThitb2();
                        }else{
                            JOptionPane.showMessageDialog(this, "Tính lương thất bại");
                        }
                        ps.close();
                    }
                    btn_LamMoiLuong.doClick();
                    conn.close();
                } catch (HeadlessException | SQLException e) {
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập số, không nhập chữ vào ô");
            System.out.println("Lỗi: " + ex.getMessage());
        }
    }//GEN-LAST:event_btn_ThemLuongActionPerformed

    private void btn_SuaLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaLuongActionPerformed
        // TODO add your handling code here:
        try{
            String MaNV, Thang, Nam, SoCong, Thuong, Phat;
            MaNV = (String) cmb_manv.getSelectedItem();
            Thang = txt_Thang.getText() ;
            Nam = txt_Nam.getText();
            SoCong = txt_SoCong.getText();
            Thuong = txt_Thuong.getText();
            Phat = txt_Phat.getText();

            int thang=0, nam=0;
            float socong=0, thuong=0, phat=0;
            if(!Thang.isEmpty() && !Nam.isEmpty() && !SoCong.isEmpty() && !Thuong.isEmpty() && !Phat.isEmpty()){
                thang = Integer.parseInt(Thang);
                nam = Integer.parseInt(Nam);
                socong = Float.parseFloat(SoCong);
                thuong = Float.parseFloat(Thuong);
                phat = Float.parseFloat(Phat);

            }
            if(MaNV.equals("") || Thang.equals("") || Nam.equals("") ||
                        SoCong.equals("") || Thuong.equals("") || Phat.equals("")){
                    JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ dữ liệu");
            }else{
                if(thang<=0 || thang >12 || nam<=0 || nam>2023 || socong < 0 || thuong < 0 || phat < 0){
                    JOptionPane.showMessageDialog(this, "Có giá trị nhập không hợp lệ", "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                if(MaNV.isEmpty()){
                    JOptionPane.showMessageDialog(this, "Sửa Thất Bại!");
                }
                conn = db.getConnection();
                try {
                    if(MaNV.equals("")||Thang.equals("")||
                        SoCong.equals("")||Thuong.equals("")||Phat.equals("")){
                        JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ dữ liệu");
                    }else{
                        PreparedStatement ps = conn.prepareStatement("Update Luong set SoCong = ?, Thuong = ?, Phat = ?, "
                            + "TongLuong = ? where MaNV = (SELECT MaNV FROM NhanVien WHERE HoTen = ?) and Thang = ? and Nam = ?");

                        ps.setFloat(1, socong);
                        ps.setFloat(2, thuong);
                        ps.setFloat(3, phat);
                        ps.setString(4, null);
                        ps.setNString(5, MaNV);
                        ps.setInt(6, thang);
                        ps.setInt(7, nam);
                        int kq = ps.executeUpdate();
                        if(kq>0){
                            JOptionPane.showMessageDialog(this, "Sửa thành công");
                            loadLaitb2();
                            HienThitb2();
                        }else{
                            JOptionPane.showMessageDialog(this, "Sửa thất bại");
                        }
                        ps.close();
                    }
                    conn.close();
                } catch (HeadlessException | SQLException e) {
                }
            }
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập, số không nhập chữ vào ô");
            System.out.println("Lỗi: " + ex.getMessage());
        }
    }//GEN-LAST:event_btn_SuaLuongActionPerformed

    private void btn_XoaLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaLuongActionPerformed
        // TODO add your handling code here:
        conn =  db.getConnection();
        String manv = (String) cmb_manv.getSelectedItem();
        try {
            PreparedStatement ps = conn.prepareStatement("Delete from Luong where MaNV = (SELECT MaNV FROM NhanVien WHERE HoTen = ?) and Thang = ? and Nam = ? ");
            ps.setNString(1, manv);
            ps.setNString(2, txt_Thang.getText().toString());
            ps.setNString(3, txt_Nam.getText().toString());
            int rowDelete = ps.executeUpdate();

            if(rowDelete > 0)
            {
                int t = JOptionPane.showConfirmDialog(this,"Ban co muon xoa?","Thong bao!", JOptionPane.YES_NO_OPTION);
                if(t == JOptionPane.YES_OPTION){
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    HienThitb2();
                    loadLaitb2();
                }else{
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");
                }
            }else {
                JOptionPane.showMessageDialog(this, "Xóa Thất Bại!");
            }
            ps.close();
            conn.close();
        }catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu: " + e.getMessage(), "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_XoaLuongActionPerformed

    private void btn_LamMoiLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiLuongActionPerformed
        // TODO add your handling code here:
        cmb_manv.setSelectedIndex(0);
        txt_Thang.setText("");
        txt_Nam.setText("");
        txt_SoCong.setText("");
        txt_Thuong.setText("");
        txt_Phat.setText("");
        txt_TongLuong.setText("");
        HienThitb2();

        cmb_manv.setEnabled(true);
        txt_Thang.setEnabled(true);
        txt_Nam.setEnabled(true);
        btn_ThemLuong.setEnabled(true);
        btn_SuaLuong.setEnabled(false);
        btn_XoaLuong.setEnabled(false);
    }//GEN-LAST:event_btn_LamMoiLuongActionPerformed

    private void btn_TimKiemLuongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_TimKiemLuongActionPerformed
        // TODO add your handling code here:
        conn = db.getConnection();
        try {
            PreparedStatement ps = conn.prepareStatement("SELECT * FROM Luong inner join NhanVien on NhanVien.MaNV = Luong.MaNV where NhanVien.HoTen like ?");
            ps.setNString(1, "%" + txt_timkiemluong.getText() + "%");
            ResultSet rs = ps.executeQuery();
            DefaultTableModel model = (DefaultTableModel) table_Luong.getModel();
            model.setRowCount(0);
            while (rs.next()) {
                Object[] rowData = {rs.getString("MaNV"), rs.getInt("Thang"), rs.getInt("Nam"), rs.getFloat("SoCong"),
                    rs.getFloat("Thuong"), rs.getFloat("Phat"), rs.getFloat("TongLuong"),};

                model.addRow(rowData);
                txt_TongLuong.setText(table_Luong.getValueAt(0, 5) + " VND");
            }
            if (model.getRowCount() > 0) {
                JOptionPane.showMessageDialog(this, "Có " + model.getRowCount() + " lương của nhân viên mà bạn muốn tìm!");
            } else {
                JOptionPane.showMessageDialog(this, "Không có lương của nhân viên nào!");
            }

            conn.close();
        } catch (HeadlessException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu: " + e.getMessage(), "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_TimKiemLuongActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ChonAnh;
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_LamMoiLuong;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_SuaLuong;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_ThemLuong;
    private javax.swing.JButton btn_TimKiem;
    private javax.swing.JButton btn_TimKiemLuong;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_XoaLuong;
    private javax.swing.ButtonGroup btngroupGT;
    private javax.swing.JComboBox<String> cbb_Nam;
    private javax.swing.JComboBox<String> cbb_Ngay;
    private javax.swing.JComboBox<String> cbb_Thang;
    private javax.swing.JComboBox<String> cmb_manv;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel label_AnhNV;
    private javax.swing.JRadioButton rbtn_Nam;
    private javax.swing.JRadioButton rbtn_Nu;
    private javax.swing.JTable table_Luong;
    private javax.swing.JTable table_NhanVien;
    private javax.swing.JTextField txt_DiaChiHienTai;
    private javax.swing.JTextField txt_HeSoLuong;
    private javax.swing.JTextField txt_HoTen;
    private javax.swing.JTextField txt_MaNV;
    private javax.swing.JTextField txt_Nam;
    private javax.swing.JTextField txt_Phat;
    private javax.swing.JTextField txt_QueQuan;
    private javax.swing.JTextField txt_SoCong;
    private javax.swing.JTextField txt_SoDienThoai;
    private javax.swing.JTextField txt_Thang;
    private javax.swing.JTextField txt_Thuong;
    private javax.swing.JTextField txt_TimKiem;
    private javax.swing.JTextField txt_TongLuong;
    private javax.swing.JTextField txt_timkiemluong;
    // End of variables declaration//GEN-END:variables
}
