/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bookshop;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Huyen
 */
public class Nhaxuatban extends javax.swing.JPanel {
    ConnectDataBase db = new ConnectDataBase();
    Connection conn;
    /**
     * Creates new form Nhaxuatban
     */
    public Nhaxuatban() {
        initComponents();
        HienTHi();
        HienTHitb2();
    }

    private  void loadLai(){
        txt_MaNXB.setText("");
        txt_TenNXB.setText("");
        txt_DiaChi.setText("");
        txt_SDT.setText("");
        txt_timkiem.setText("");
    }
    
    public void HienTHi(){
        conn =  db.getConnection();

        try {
            Statement st =  conn.createStatement();
            String query = "Select * from NhaXuatBan";
            ResultSet rs =  st.executeQuery(query);
            DefaultTableModel model  = new DefaultTableModel();
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            for(int columnIndex = 1; columnIndex <= columnCount; columnIndex++) 
            {
                model.addColumn(metaData.getColumnLabel(columnIndex));
            }
            while(rs.next()) 
            {
                Object[] rowData = new Object[columnCount];
                for(int i=0; i<columnCount; i++) 
                {
                    rowData[i] = rs.getObject(i + 1); 
                }
                model.addRow(rowData);
            }
            table_NXB.setModel(model);
            st.close();
            rs.close();
            conn.close();
	} catch (SQLException e1) {
            e1.toString();
	}
    }
    
    public void HienTHitb2(){
        conn =  db.getConnection();
        try {
            Statement st =  conn.createStatement();
            String query = "Select * from NhaXuatBan";
            ResultSet rs =  st.executeQuery(query);
            DefaultTableModel model  = new DefaultTableModel();
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            for(int columnIndex = 1; columnIndex <= columnCount; columnIndex++) 
            {
                model.addColumn(metaData.getColumnLabel(columnIndex));
            }
            while(rs.next()) 
            {
                Object[] rowData = new Object[columnCount];
                for(int i=0; i<columnCount; i++) 
                {
                    rowData[i] = rs.getObject(i + 1); 
                }
                model.addRow(rowData);
            }
            table_NXB2.setModel(model);
            st.close();
            rs.close();
            conn.close();
	} catch (SQLException e1) {
            // TODO Auto-generated catch block
            e1.toString();
	}
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt_timkiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_NXB = new javax.swing.JTable();
        btn_timkiem = new javax.swing.JButton();
        btn_hienthi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_NXB2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txt_MaNXB = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_TenNXB = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_DiaChi = new javax.swing.JTextField();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txt_SDT = new javax.swing.JTextField();
        btn_Xoa = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txt_timkiem.setBackground(new java.awt.Color(255, 255, 255));
        txt_timkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_timkiem.setForeground(new java.awt.Color(0, 0, 0));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        table_NXB.setBackground(new java.awt.Color(255, 255, 255));
        table_NXB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_NXB.setForeground(new java.awt.Color(0, 0, 0));
        table_NXB.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_NXB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_NXBMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_NXB);

        btn_timkiem.setBackground(new java.awt.Color(255, 255, 255));
        btn_timkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_timkiem.setForeground(new java.awt.Color(0, 0, 0));
        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        btn_timkiem.setText("Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        btn_hienthi.setBackground(new java.awt.Color(255, 255, 255));
        btn_hienthi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_hienthi.setForeground(new java.awt.Color(0, 0, 0));
        btn_hienthi.setText("Hiện thị tất cả");
        btn_hienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hienthiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nhập thông tin:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/nxb2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_hienthi)
                    .addComponent(btn_timkiem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_hienthi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jTabbedPane2.addTab("Tìm kiếm Nhà Xuất Bản", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(824, 647));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        table_NXB2.setBackground(new java.awt.Color(255, 255, 255));
        table_NXB2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_NXB2.setForeground(new java.awt.Color(0, 0, 0));
        table_NXB2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_NXB2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_NXB2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_NXB2);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Mã Nhà Xuất Bản:");

        txt_MaNXB.setBackground(new java.awt.Color(255, 255, 255));
        txt_MaNXB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_MaNXB.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tên Nhà Xuất Bản:");

        txt_TenNXB.setBackground(new java.awt.Color(255, 255, 255));
        txt_TenNXB.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_TenNXB.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Địa Chỉ:");

        txt_DiaChi.setBackground(new java.awt.Color(255, 255, 255));
        txt_DiaChi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_DiaChi.setForeground(new java.awt.Color(0, 0, 0));

        btn_Them.setBackground(new java.awt.Color(255, 255, 255));
        btn_Them.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Them.setForeground(new java.awt.Color(0, 0, 0));
        btn_Them.setText("Thêm Nhà Xuất Bản");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(255, 255, 255));
        btn_Sua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(0, 0, 0));
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Số Điện Thoại:");

        txt_SDT.setBackground(new java.awt.Color(255, 255, 255));
        txt_SDT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_SDT.setForeground(new java.awt.Color(0, 0, 0));

        btn_Xoa.setBackground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(0, 0, 0));
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_LamMoi.setBackground(new java.awt.Color(255, 255, 255));
        btn_LamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_LamMoi.setForeground(new java.awt.Color(0, 0, 0));
        btn_LamMoi.setText("Reset");
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_TenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_MaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_DiaChi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Them)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_MaNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_TenNXB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_DiaChi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_SDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Thêm Nhà Xuất Bản", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 678, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void table_NXBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_NXBMouseClicked
        // TODO add your handling code here:
        table_NXB.setDefaultEditor(Object.class, null);
    }//GEN-LAST:event_table_NXBMouseClicked

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        conn = db.getConnection();
        try {
            DefaultTableModel model = (DefaultTableModel)table_NXB.getModel();
            model.setRowCount(0);
                
            if(txt_timkiem.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Vui Lòng nhập thông tin cần tìm kiếm");
                HienTHi();
            } else{
                String sql = "select * from NhaXuatBan where TenNhaXuatBan like N'%" + txt_timkiem.getText() + "%'";
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                
                while(rs.next()){
                    Object[] row = new Object[4];
                    row[0] = rs.getString("MaNhaXuatBan");
                    row[1] = rs.getString("TenNhaXuatBan");
                    row[2] = rs.getString("DiaChi");
                    row[3] = rs.getString("DienThoai");
                    
                    model.addRow(row);
                    
                }
                if(model.getRowCount() > 0)
                {
                    JOptionPane.showMessageDialog(this, "Có " + model.getRowCount() + " sách mà bạn muốn tìm!");
                    loadLai();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Không tìm thấy kết quả");
                }
                rs.close();
                st.close();
                conn.close();
            }
        } catch (Exception e) {
            e.toString();
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_hienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hienthiActionPerformed
        // TODO add your handling code here:
        HienTHi();
    }//GEN-LAST:event_btn_hienthiActionPerformed

    private void table_NXB2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_NXB2MouseClicked
        // TODO add your handling code here:
        int i = table_NXB2.getSelectedRow();
        table_NXB2.setDefaultEditor(Object.class, null);
        if(i>=0){
            txt_MaNXB.setText(table_NXB2.getValueAt(i, 0)+"");
            txt_TenNXB.setText(table_NXB2.getValueAt(i, 1)+"");
            txt_DiaChi.setText(table_NXB2.getValueAt(i, 2)+"");
            txt_SDT.setText(table_NXB2.getValueAt(i, 3)+"");
        }
        txt_MaNXB.setEnabled(false);
        btn_Them.setEnabled(false);
        btn_Sua.setEnabled(true);
        btn_Xoa.setEnabled(true);
    }//GEN-LAST:event_table_NXB2MouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        conn = db.getConnection();
        try {
            if(txt_MaNXB.getText().equals("")||txt_TenNXB.getText().equals("")||
                    txt_DiaChi.getText().equals("")||txt_SDT.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ dữ liệu");
            }else{
                StringBuffer sb = new StringBuffer();
                String querry = "select MaNhaXuatBan from NhaXuatBan where MaNhaXuatBan = '" + txt_MaNXB.getText()+"'";
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(querry);
                if(rs.next()){
                    sb.append("Mã nhà xuất bản này đã tồn tại");
                }
                if(sb.length() > 0){//nếu if kia đúng thig nó sẽ thêm vào sb 1 đoạn string,ktra độ dài chuỗi này nếu lớn hơn 0 tức là có thông báo
                    JOptionPane.showMessageDialog(this, sb.toString());
                }else{ 
                    String sql = "insert into NhaXuatBan values('"+txt_MaNXB.getText()+"',N'"+txt_TenNXB.getText()+"',N'"+txt_DiaChi.getText()+"',"
                            + "'"+txt_SDT.getText()+"')";
                    st = conn.createStatement();
                    int kq = st.executeUpdate(sql);
                    if(kq>0){
                        JOptionPane.showMessageDialog(this, "Thêm thành công");
                        loadLai();
                        HienTHitb2();
                    }else{
                        JOptionPane.showMessageDialog(this, "Thêm thất bại");                        
                    }
                    st.close();
                }
                conn.close();
                
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu: " + e.getMessage(), "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        conn = db.getConnection();
        try {
            if(txt_MaNXB.getText().equals("")||txt_TenNXB.getText().equals("")||
                    txt_DiaChi.getText().equals("")||txt_SDT.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ dữ liệu");
            }else{
                String sql = "Update NhaXuatBan set TenNhaXuatBan = N'"+txt_TenNXB.getText()+"',DiaChi = N'"+txt_DiaChi.getText()+"',"
                            +"DienThoai = '"+txt_SDT.getText()+"'where MaNhaXuatBan = '"+txt_MaNXB.getText()+"'";
                Statement st = conn.createStatement();
                int kq = st.executeUpdate(sql);
                if(kq>0){
                    JOptionPane.showMessageDialog(this, "Sửa thành công");
                    loadLai();
                    HienTHitb2();
                }else{
                    JOptionPane.showMessageDialog(this, "Sửa thất bại");                        
                }
                st.close();
            }
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu: " + e.getMessage(), "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        conn = db.getConnection();
        try {
                Statement st = conn.createStatement();
                String sql = "delete from NhaXuatBan where MaNhaXuatBan = '"+txt_MaNXB.getText()+"'";
                st = conn.createStatement();
                int t = JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa?","Thông báo!", JOptionPane.YES_NO_OPTION);
                if(t == JOptionPane.YES_OPTION){
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    loadLai();
                    HienTHitb2();
                }else{
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");                        
                }
                st.close();
                conn.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Mã Nhà Xuất Bản " + txt_MaNXB.getText().toString() + " đang liên kết với Bảng Sách nên bạn không thể xóa được");
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        // TODO add your handling code here:
        loadLai();
        HienTHi();
        
        txt_MaNXB.setEnabled(true);
        btn_Them.setEnabled(true);
        btn_Sua.setEnabled(false);
        btn_Xoa.setEnabled(false);
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        // TODO add your handling code here:
       HienTHitb2();
       HienTHi();
    }//GEN-LAST:event_jTabbedPane2StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_hienthi;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable table_NXB;
    private javax.swing.JTable table_NXB2;
    private javax.swing.JTextField txt_DiaChi;
    private javax.swing.JTextField txt_MaNXB;
    private javax.swing.JTextField txt_SDT;
    private javax.swing.JTextField txt_TenNXB;
    private javax.swing.JTextField txt_timkiem;
    // End of variables declaration//GEN-END:variables
}
