/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package bookshop;

import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Huyen
 */
public class Tacgia extends javax.swing.JPanel {

    ConnectDataBase db = new ConnectDataBase();
    Connection conn;
    /**
     * Creates new form Tacgia
     */
    public Tacgia() {
        initComponents();
        Hienthi();
        Hienthi2();
    }
    
    void loadlai(){
        txt_matg.setText(null);
        txt_tongcb.setText(null);
        txt_phocb.setText(null);
        txt_lienhe.setText(null);
    }
    
    public void Hienthi()
    {
        conn =  db.getConnection();

        try {
            Statement st =  conn.createStatement();
            String query = "Select * from TacGia";
            ResultSet rs =  st.executeQuery(query);
            DefaultTableModel model  = new DefaultTableModel();
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            for(int columnIndex = 1; columnIndex <= columnCount; columnIndex++) 
            {
                model.addColumn(metaData.getColumnLabel(columnIndex));
            }
            while(rs.next()) 
            {
                Object[] rowData = new Object[columnCount];
                for(int i=0; i<columnCount; i++) 
                {
                    rowData[i] = rs.getObject(i + 1); 
                }
                model.addRow(rowData);
            }
            table_tacgia.setModel(model);
            st.close();
            rs.close();
            conn.close();
	} catch (SQLException e1) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu: " + e1.getMessage(), "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
	}
    }
    public void Hienthi2()
    {
        conn =  db.getConnection();

        try {
            Statement st =  conn.createStatement();
            String query = "Select * from TacGia";
            ResultSet rs =  st.executeQuery(query);
            DefaultTableModel model  = new DefaultTableModel();
            ResultSetMetaData metaData = rs.getMetaData();
            int columnCount = metaData.getColumnCount();
            for(int columnIndex = 1; columnIndex <= columnCount; columnIndex++) 
            {
                model.addColumn(metaData.getColumnLabel(columnIndex));
            }
            while(rs.next()) 
            {
                Object[] rowData = new Object[columnCount];
                for(int i=0; i<columnCount; i++) 
                {
                    rowData[i] = rs.getObject(i + 1); 
                }
                model.addRow(rowData);
            }
            table_tacgia2.setModel(model);
            st.close();
            rs.close();
            conn.close();
	} catch (SQLException e1) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu: " + e1.getMessage(), "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
	}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane2 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        txt_timkiem = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_tacgia = new javax.swing.JTable();
        btn_timkiem = new javax.swing.JButton();
        btn_hienthi = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table_tacgia2 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        txt_matg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txt_tongcb = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txt_phocb = new javax.swing.JTextField();
        btn_Them = new javax.swing.JButton();
        btn_Sua = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        txt_lienhe = new javax.swing.JTextField();
        btn_Xoa = new javax.swing.JButton();
        btn_LamMoi = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jTabbedPane2.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setForeground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTabbedPane2.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jTabbedPane2StateChanged(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        txt_timkiem.setBackground(new java.awt.Color(255, 255, 255));
        txt_timkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_timkiem.setForeground(new java.awt.Color(0, 0, 0));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        table_tacgia.setBackground(new java.awt.Color(255, 255, 255));
        table_tacgia.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_tacgia.setForeground(new java.awt.Color(0, 0, 0));
        table_tacgia.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_tacgia.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_tacgiaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(table_tacgia);

        btn_timkiem.setBackground(new java.awt.Color(255, 255, 255));
        btn_timkiem.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_timkiem.setForeground(new java.awt.Color(0, 0, 0));
        btn_timkiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/search.png"))); // NOI18N
        btn_timkiem.setText("Tìm kiếm");
        btn_timkiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemActionPerformed(evt);
            }
        });

        btn_hienthi.setBackground(new java.awt.Color(255, 255, 255));
        btn_hienthi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_hienthi.setForeground(new java.awt.Color(0, 0, 0));
        btn_hienthi.setText("Hiện thị tất cả");
        btn_hienthi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_hienthiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel4.setText("Nhập thông tin:");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/tacgia2.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_hienthi)
                    .addComponent(btn_timkiem))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_timkiem, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btn_hienthi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        jTabbedPane2.addTab("Tìm kiếm Tác Giả", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(824, 647));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        table_tacgia2.setBackground(new java.awt.Color(255, 255, 255));
        table_tacgia2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        table_tacgia2.setForeground(new java.awt.Color(0, 0, 0));
        table_tacgia2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table_tacgia2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                table_tacgia2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(table_tacgia2);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel5.setText("Mã Tác Giả:");

        txt_matg.setBackground(new java.awt.Color(255, 255, 255));
        txt_matg.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_matg.setForeground(new java.awt.Color(0, 0, 0));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel6.setText("Tên Tổng Chủ Biên:");

        txt_tongcb.setBackground(new java.awt.Color(255, 255, 255));
        txt_tongcb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_tongcb.setForeground(new java.awt.Color(0, 0, 0));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel7.setText("Tên Phó Chủ Biên:");

        txt_phocb.setBackground(new java.awt.Color(255, 255, 255));
        txt_phocb.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_phocb.setForeground(new java.awt.Color(0, 0, 0));

        btn_Them.setBackground(new java.awt.Color(255, 255, 255));
        btn_Them.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Them.setForeground(new java.awt.Color(0, 0, 0));
        btn_Them.setText("Thêm Tác Giả");
        btn_Them.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ThemActionPerformed(evt);
            }
        });

        btn_Sua.setBackground(new java.awt.Color(255, 255, 255));
        btn_Sua.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Sua.setForeground(new java.awt.Color(0, 0, 0));
        btn_Sua.setText("Sửa");
        btn_Sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SuaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel14.setText("Liên Hệ:");

        txt_lienhe.setBackground(new java.awt.Color(255, 255, 255));
        txt_lienhe.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txt_lienhe.setForeground(new java.awt.Color(0, 0, 0));

        btn_Xoa.setBackground(new java.awt.Color(255, 255, 255));
        btn_Xoa.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Xoa.setForeground(new java.awt.Color(0, 0, 0));
        btn_Xoa.setText("Xóa");
        btn_Xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_XoaActionPerformed(evt);
            }
        });

        btn_LamMoi.setBackground(new java.awt.Color(255, 255, 255));
        btn_LamMoi.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_LamMoi.setForeground(new java.awt.Color(0, 0, 0));
        btn_LamMoi.setText("Reset");
        btn_LamMoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_LamMoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 794, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_tongcb, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_matg, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_phocb, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_lienhe, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Them)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txt_matg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Them, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txt_tongcb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txt_phocb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_Sua, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txt_lienhe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_LamMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane2.addTab("Thêm Tác Giả", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane2)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void table_tacgiaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_tacgiaMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_table_tacgiaMouseClicked

    private void btn_timkiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemActionPerformed
        // TODO add your handling code here:
        conn = db.getConnection();
        try {
            DefaultTableModel model = (DefaultTableModel)table_tacgia.getModel();
            model.setRowCount(0);
                
            if(txt_timkiem.getText().equals(""))
            {
                JOptionPane.showMessageDialog(this, "Bạn chưa nhập thông tin cần tìm");
                Hienthi();
            } else{
                String sql = "select * from TacGia where TenTongChuBien like N'%" + txt_timkiem.getText() + "%'" + "or TenPhoChuBien like N'%" + txt_timkiem.getText() + "%'";
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(sql);
                
                while(rs.next()){
                    Object[] row = new Object[4];
                    row[0] = rs.getString("MaTacGia");
                    row[1] = rs.getString("TenTongChuBien");
                    row[2] = rs.getString("TenPhoChuBien");
                    row[3] = rs.getString("LienHe");
                    
                    model.addRow(row);
                    
                }
                if(model.getRowCount() > 0)
                {
                    JOptionPane.showMessageDialog(this, "Có " + model.getRowCount() + " tác giả mà bạn muốn tìm!");
                    loadlai();
                }
                else{
                    JOptionPane.showMessageDialog(this, "Không tìm thấy kết quả");
                }
                rs.close();
                st.close();
                conn.close();
            }
        } catch (Exception e) {
            e.toString();
        }
    }//GEN-LAST:event_btn_timkiemActionPerformed

    private void btn_hienthiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_hienthiActionPerformed
        // TODO add your handling code here:
        txt_timkiem.setText(null);
        Hienthi();
    }//GEN-LAST:event_btn_hienthiActionPerformed

    private void table_tacgia2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_table_tacgia2MouseClicked
        // TODO add your handling code here:
        int row = table_tacgia2.getSelectedRow();
        if (row >= 0)
        {
            txt_matg.setText(table_tacgia2.getValueAt(row, 0).toString());
            txt_tongcb.setText(table_tacgia2.getValueAt(row, 1).toString());
            txt_phocb.setText(table_tacgia2.getValueAt(row, 2).toString());
            txt_lienhe.setText(table_tacgia2.getValueAt(row, 3).toString());
        }
        btn_Xoa.setEnabled(true);
        btn_Sua.setEnabled(true);
        btn_Them.setEnabled(false);
        txt_matg.setEnabled(false);
    }//GEN-LAST:event_table_tacgia2MouseClicked

    private void btn_ThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ThemActionPerformed
        // TODO add your handling code here:
        conn = db.getConnection();
        try {
            if(txt_matg.getText().equals("")||txt_tongcb.getText().equals("")||
                    txt_phocb.getText().equals("")||txt_lienhe.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ dữ liệu");
            }
            else
            {
                StringBuffer sb = new StringBuffer();
                String querry = "select MaTacGia from TacGia where MaTacGia = '" + txt_matg.getText()+"'";
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(querry);
                if(rs.next())
                {
                    sb.append("Mã nhà xuất bản này đã tồn tại");
                }
                if(sb.length() > 0)
                {//nếu if kia đúng thig nó sẽ thêm vào sb 1 đoạn string,ktra độ dài chuỗi này nếu lớn hơn 0 tức là có thông báo
                    JOptionPane.showMessageDialog(this, sb.toString());
                }
                else
                { 
                    String sql = "insert into TacGia values('"+txt_matg.getText()+"',N'"+txt_tongcb.getText()+"',N'"+txt_phocb.getText()+"',N'"+txt_lienhe.getText()+"')";
                    st = conn.createStatement();
                    int kq = st.executeUpdate(sql);
                    if(kq>0)
                    {
                        JOptionPane.showMessageDialog(this, "Thêm thành công");
                        loadlai();
                        Hienthi2();
                    }
                    else
                    {
                        JOptionPane.showMessageDialog(this, "Thêm thất bại");                        
                    }
                    st.close();
                }
                conn.close();
                
            }
        } 
        catch (Exception e) 
        {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu: " + e.getMessage(), "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_ThemActionPerformed

    private void btn_SuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SuaActionPerformed
        // TODO add your handling code here:
        conn = db.getConnection();
        try {
            if(txt_matg.getText().equals("")||txt_tongcb.getText().equals("")||
                    txt_phocb.getText().equals("")||txt_lienhe.getText().equals("")){
                JOptionPane.showMessageDialog(this, "Bạn cần nhập đủ dữ liệu");
            }else{
                String sql = "Update TacGia set TenTongChuBien = N'"+txt_tongcb.getText()+"',TenPhoChuBien = N'"+txt_phocb.getText()+"',"
                            +"LienHe = '"+txt_lienhe.getText()+"'where MaTacGia = '"+txt_matg.getText()+"'";
                Statement st = conn.createStatement();
                int kq = st.executeUpdate(sql);
                if(kq>0){
                    JOptionPane.showMessageDialog(this, "Sửa thành công");
                    loadlai();
                    Hienthi2();
                }else{
                    JOptionPane.showMessageDialog(this, "Sửa thất bại");                        
                }
                st.close();
            }
            conn.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Lỗi nhập liệu: " + e.getMessage(), "Thông báo lỗi", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_SuaActionPerformed

    private void btn_XoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_XoaActionPerformed
        // TODO add your handling code here:
        conn = db.getConnection();
        try {
            String matg = txt_matg.getText();
            if (matg == null || matg.trim().isEmpty()) 
            {
            JOptionPane.showMessageDialog(this, "Vui lòng nhập mã tác giả trước khi xóa");
            return;
            }
            else
            {
                Statement st = conn.createStatement();
                String sql = "delete from TacGia where matacgia = '"+matg+"'";
                st = conn.createStatement();
                int t = JOptionPane.showConfirmDialog(this,"Bạn có muốn xóa?","Thông báo!", JOptionPane.YES_NO_OPTION);
                if(t == JOptionPane.YES_OPTION){
                    st.executeUpdate(sql);
                    JOptionPane.showMessageDialog(this, "Xóa thành công");
                    loadlai();
                    Hienthi2();
                }else{
                    JOptionPane.showMessageDialog(this, "Xóa thất bại");                        
                }
                st.close();
                conn.close();
            }
        }
        catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Mã Tác giả " + txt_matg.getText().toString() + " đang liên kết với Bảng Sách nên bạn không thể xóa được");
        }
    }//GEN-LAST:event_btn_XoaActionPerformed

    private void btn_LamMoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_LamMoiActionPerformed
        // TODO add your handling code here:
        loadlai();
        Hienthi2();
        txt_matg.setEnabled(true);
        btn_Xoa.setEnabled(false);
        btn_Sua.setEnabled(false);
        btn_Them.setEnabled(true);
    }//GEN-LAST:event_btn_LamMoiActionPerformed

    private void jTabbedPane2StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jTabbedPane2StateChanged
        // TODO add your handling code here:
        Hienthi();
        Hienthi2();
        btn_Xoa.setEnabled(false);
        btn_Sua.setEnabled(false);
    }//GEN-LAST:event_jTabbedPane2StateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_LamMoi;
    private javax.swing.JButton btn_Sua;
    private javax.swing.JButton btn_Them;
    private javax.swing.JButton btn_Xoa;
    private javax.swing.JButton btn_hienthi;
    private javax.swing.JButton btn_timkiem;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTable table_tacgia;
    private javax.swing.JTable table_tacgia2;
    private javax.swing.JTextField txt_lienhe;
    private javax.swing.JTextField txt_matg;
    private javax.swing.JTextField txt_phocb;
    private javax.swing.JTextField txt_timkiem;
    private javax.swing.JTextField txt_tongcb;
    // End of variables declaration//GEN-END:variables
}
